### ISSUE TITLE
run tc_profiling/compile.sh error

### ISSUE THREAD

**Issue by heliqi** [spcl/substation#1]
I run the 'tc_profiling/compile.sh', show error:
```
cublas-gemm.cpp: In function 'int main(int argc, char **argv)':
cublas-gemm.cpp: 26:10: error: 'err' does not name a type
               auto err = (expr);  
cublas-gemm.cpp: 37:3: note: in expansion of macro ‘CUDA_CHECK’
               CUDA_CHECK(cublasCreate(&handle));x
....
 
```
GPU type: V100
cuda version:10.1

What is your compilation environment?

**Comment by ndryden** [comment]
What version of GCC are you using? This appears to be an error with C++11 support in your compiler not being enabled.

It builds fine with CUDA 10.1 and GCC 7.3.1 for me, but I can reproduce this with GCC 4.9.3. Can you use a newer compiler? Or try editing `compile.sh` to pass `-std=c++11`?

**Comment by heliqi** [comment]
Thanks,My gcc version is 4.8.....
After I upgrade the GCC version,it's working!
