### ISSUE TITLE
How to compile & execute Substation encoder

### ISSUE THREAD

**Issue by richardschulze** [spcl/substation#5]
Hi,

I am trying to execute the Substation encoder layer provided in the `pytorch_module` folder. According to the readme I am trying to execute the following command

    python run_encoder.py --batch-size 8 --max-seq-len 512 --num-heads 16 --emb-size 1024 --layout layouts-bert-b8-l512-h16-e1024.pickle

but this results in an error message:

    OSError: ./compilation_dir/26e5dc71cb611d368b14bab45256feed/./encoder.so: cannot open shared object file: No such file or directory

I have then tried to run `make encoder` to hopefully build the `encoder.so` library. This unfortunately fails as well:

    encoder.cu:30:10: fatal error: encoder_parameters.cuh: No such file or directory

even when I set `CPATH` to include the `compilation_dir` folder:

    nvcc --compiler-options -Wfatal-errors -O3 -o encoder encoder.cu -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -lcublas
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function _start':
    (.text+0x24): undefined reference to main'

Could you help me get this running or point me to the corresponding part of the readme on how to fix this?
Many thanks in advance!

**Comment by richardschulze** [comment]
I got it working by removing the `compilation_dir` folder, setting `CPATH` as above, and then calling `run_encoder.py` instead of calling `make` manually.

**Comment by tbennun** [comment]
As an additional note, when you tried to compile manually, you needed to use `-shared -o libencoder.so` because the encoder is a shared library, not an executable.
